### ISSUE TITLE
Feature Request : include all race-weekend sessions

### ISSUE THREAD

**Issue by Zixim** [delzear/hass-formulaoneapi#33]
It might be nice if FP1, 2, 3  & Qualy could also be exposed ?

**Comment by delzear** [comment]
They actually are, you just need to implement them in your front end.
If you do, please post it here so others can have it!

**Comment by Zixim** [comment]
This should be more elegant in case of missing P3 or when Sprint weekends:
```yaml
{% set nr = state_attr('sensor.formula_one_sensor', 'next_race')  %}
{% set nr = nr if not nr is none else {} %}

P1: {{ nr.get('FirstPractice', {}).get('date') }} {{ nr.get('FirstPractice', {}).get('time') }}
P2: {{ nr.get('SecondPractice', {}).get('date') }} {{ nr.get('SecondPractice', {}).get('time') }}
P3: {{ nr.get('ThirdPractice', {}).get('date') }} {{ nr.get('ThirdPractice', {}).get('time') }}
SP: {{ nr.get('Sprint', {}).get('date') }} {{ nr.get('Sprint', {}).get('time') }}
Q : {{ nr.get('Qualifying', {}).get('date') }} {{ nr.get('Qualifying', {}).get('time') }}
```
copy/paste it into DeveloperTools/Template, at time of writing it results in : 
```
P1: 2022-07-08 11:30:00Z
P2: 2022-07-09 10:30:00Z
P3: None None
SP: 2022-07-09 14:30:00Z
Q : 2022-07-08 15:00:00Z
```

There's lots of room for improvement, hopefully someone will take this further.
