### ISSUE TITLE
Platform error sensor.formula_oneapi - Integration 'formula_oneapi' not found.

### ISSUE THREAD

**Issue by jeusch8** [delzear/hass-formulaoneapi#62]
Hello, sorry Im newer to HA but I followed your instructions and everytime I add the 
sensor:
  - platform: formulaone_api
I cant get it to load. Ive tried to manually install it and add the custom repository from the HACS. If you have any insight as to why this may be happening Id appreciate it.
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.11
    - 192.168.50.32

lovelace:
  resources:
    - url: /hacsfiles/formulaone-card/formulaone-card.js
      type: module
sensor:
  - platform: formula_oneapi
camera:
  - platform: generic
    still_image_url: https://s.w-x.co/staticmaps/wu/wu/wxtype1200_cur/conus/animate.png
    name: KC Weather Radar

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```
![6fa7e543022a911b302ecafc13190382](https://user-images.githubusercontent.com/58417871/208726625-02bfd7e9-12b4-46ba-bc5b-b6de221ac530.png)
